// import { Listing } from '../components/tables/columns';

export const tableData = [
  {
    id: 'm5gr84i9',
    amount: 316,
    status: 'success',
    location: 'Nepal, Kathmandu',
    title: 'Hotel in Nepal - Kathmandu',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '3u1reuv4',
    amount: 242,
    status: 'success',
    location: 'Morocco, Marrakech',
    title: 'Hotel in Morocco - Marrakech',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: 'derv1ws0',
    amount: 837,
    status: 'processing',
    location: 'Spain, Barcelona',
    title: 'Hotel in Spain - Barcelona',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '5kma53ae',
    amount: 874,
    status: 'success',
    location: 'Saudi Arabia, Riad',
    title: 'Hotel in Saudi Arabia - Riad',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: 'bhqecj4p',
    amount: 721,
    status: 'failed',
    location: 'United States, New York',
    title: 'Hotel in United States - New York',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: 'bhqec54p',
    amount: 101,
    status: 'failed',
    location: 'United States, New York',
    title: 'Hotel in United States - New York',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '1015gr84i9',
    amount: 316,
    status: 'success',
    location: 'Nepal, Kathmandu',
    title: 'Hotel in Nepal - Kathmandu',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '101u1reuv4',
    amount: 242,
    status: 'success',
    location: 'Morocco, Marrakech',
    title: 'Hotel in Morocco - Marrakech',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '101erv1ws0',
    amount: 837,
    status: 'processing',
    location: 'Spain, Barcelona',
    title: 'Hotel in Spain - Barcelona',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '101kma53ae',
    amount: 874,
    status: 'success',
    location: 'Saudi Arabia, Riad',
    title: 'Hotel in Saudi Arabia - Riad',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '101hqecj4p',
    amount: 721,
    status: 'failed',
    location: 'United States, New York',
    title: 'Hotel in United States - New York',
    description: 'This is my description',
    image: '/images/1.png',
  },
  {
    id: '101hqec54p',
    amount: 101,
    status: 'failed',
    location: 'United States, New York',
    title: 'Hotel in United States - New York',
    description: 'This is my description',
    image: '/images/1.png',
  },
];

export const ListingDetailsFields = {
  title: {
    name: 'Listing title',
    description:
      'Your listing title should highlight what makes your place special.',
    type: 'text',
    input: 'title',
  },
  description: {
    name: 'Listing Description',
    description:
      "Give guests a sense of what it's like to stay at your place, including why they'll love staying there.",
    type: 'textarea',
    input: 'description',
  },
  location: {
    name: 'Location',
    description: "Your listing's location will be shown on the map to guests.",
    type: 'text',
    input: 'location',
  },
  property: {
    name: 'Property type',
    description: 'What kind of place are you listing?',
    type: 'select',
    input: 'property',
  },
  rooms: {
    name: 'Rooms and spaces',
    description: 'How many guests will have a comfortable place to sleep?',
    type: 'select',
    input: 'rooms',
  },
};
