export const ProductData = [
  {
    id: '1',
    title: 'Hotel Telsa in athe ',
    subTitle: 'Dhaka, mirupur gulsan ',
    description: 'description should be here',
    price: 50,
    rating: { rate: 6.5, count: 100 },
    img: '/assets/Accommodation_A cozy gem overlooking Bwindi Impenetrable National Park.jpg',
    category: 'home',
  },
  {
    id: '2',
    title: 'Title should be here',
    subTitle: 'subTitle should be here',
    description: 'description should be here',
    price: 55,
    rating: { rate: 8.5, count: 100 },
    img: '/assets/Biwindi National Park Area, Uganda, Africa.jpg',
    category: 'home',
  },
  {
    id: '3',
    title: 'Title should be here',
    subTitle: 'subTitle should be here',
    description: 'description should be here',
    price: 45,
    rating: { rate: 4.5, count: 100 },
    img: '/assets/Things to do from home_Online Events.jpg',
    category: 'home applienses',
  },
  {
    id: '4',
    title: 'Title should be here',
    subTitle: 'subTitle should be here',
    description: 'description should be here',
    price: 105,
    rating: { rate: 6.7, count: 100 },
    img: '/assets/Things to do from home_Online Events.jpg',
    category: 'rent',
  },
];
